// REGISTER TYPES
export const USER_REGISTER  = 'USER_REGISTER'
export const USER_ERROR = 'USER_ERROR'

// LOGIN TYPES
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_ERROR ='USER_LOGIN_ERROR'

// SIGN OUT TYPES
export const USER_SIGN_OUT = 'USER_SIGN_OUT'

//PRODUCT TYPES
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS'
export const PRODUCT_ERROR = 'PRODUCT_ERROR' 